context:
  name: PALP
  version: "2.21.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/ariostas/PALP/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 463b63eb4b0c7e24f5f9f5eacb0a5ff8ea81ec008dab7fea5058b8ec825d544f

build:
  # Uncomment the following line if the package is pure Python and the recipe is exactly the same for all platforms.
  # It is okay if the dependencies are not built for all platforms/versions, although selectors are still not allowed.
  # See https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python for more details.
  # noarch: python
  # If the installation is complex, or different between Unix and Windows, use separate build.bat and build.sh files instead of this key.
  # By default, the package will be built for the Python versions supported by conda-forge and for all major OSs.
  # Uncomment the following lines to limit to Python 3.5 and newer (for example)
  # skip:
  #   - match(python, "<3.5")
  # or the following to limit to Windows.
  # skip:
  #   - win
  number: 0
  skip: [win]
  script: |
    cmake -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_INSTALL_LIBDIR=lib -S $SRC_DIR -B $SRC_DIR/build
    cmake --build $SRC_DIR/build
    cmake --build $SRC_DIR/build --target install

requirements:
  build:
    - ${{ compiler('c') }}
    # - ${{ stdlib('c') }}
    - cmake
    - make
  # host:
  # run:

tests:
  - package_contents:
      include:
        - Mori.h

about:
  homepage: http://hep.itp.tuwien.ac.at/~kreuzer/CY/CYpalp.html
  summary: "PALP: a Package for Analyzing Lattice Polytopes"
  description: |
    simplejson is a simple, fast, complete, correct and extensible
    JSON <https://json.org> encoder and decoder for Python 2.5+ and
    Python 3.3+. It is pure Python code with no dependencies, but includes
    an optional C extension for a serious speed boost.
  # Remember to specify the license variants for BSD, Apache, GPL, and LGPL.
  # Use the SPDX identifier, e.g: GPL-2.0-only instead of GNU General Public License version 2.0
  # See https://spdx.org/licenses/
  license: MIT
  # It is required to include a license file in the package,
  # (even if the license doesn't require it) using the license_file entry.
  # Please also note that some projects have multiple license files which all need to be added using a valid yaml list.
  # See https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#license-file
  license_file: LICENSE.txt
  # The documentation and repository URLs are optional.
  documentation: https://simplejson.readthedocs.io/
  repository: https://github.com/simplejson/simplejson

extra:
  recipe-maintainers:
    - ariostas
